apiVersion: v1
kind: Service
metadata:
  name: recipe-api-np
spec:
  type: NodePort
  selector:
    app: recipe-api
  ports:
    - name: recipe-api
      protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30036