# resources:
# - repo: self

stages:
- stage: CreateMigrationBundle
  displayName: 'Create Migration Bundle'
  jobs:
  - job: 'Install_EF_Tool'
    displayName: 'Install EF Tool'
    steps:
    - task: DotNetCoreCLI@2
      displayName: New Manifest for Tool
      inputs:
        command: custom
        custom: 'new '
        arguments: tool-manifest
    - task: DotNetCoreCLI@2
      displayName: Install EF Tool
      inputs:
        command: custom
        custom: 'tool '
        arguments: install dotnet-ef
    - task: DotNetCoreCLI@2
      displayName: Create Migration Bundle
      inputs:
        command: custom
        custom: 'ef '
        arguments: migrations bundle -o RecipeBundle.exe --project "Code/Data/Recipe.Data.Entity/Recipe.Data.Entity.csproj"
    - script: |
        ls
        echo "----"
        ls -ld $(Build.SourcesDirectory)
        echo "----"
    - task: Bash@3
      displayName: Bash Script
      inputs:
        targetType: 'inline'
        script: RecipeBundle.exe --connection "Server=recipe-azuresql-server-124703172.database.windows.net;Database=Recipe;User Id=azureuser;Password=Pa294w0rD-124703172"
