# trigger:
# - main

# resources:
# - repo: self

# you have to setup a step to use powershell to get the storage key once you've setup the backend storage account
# key for the terraform state file

stages:
- stage: Provision
  displayName: 'Terraform Azure Environment'
  jobs: 
  - job: Secrets
    displayName: 'Get Azure Key Vault Secrets'
    steps:
    - task: AzureKeyVault@2
      inputs:
        azureSubscription: 'alfredoball Azure Resource Manager'
        KeyVaultName: 'recipe-dev-kv'
        SecretsFilter: '*'
        RunAsPreJob: true
  - job: Provision
    displayName: 'Provisioning Container Instance'
    dependsOn: Secrets
    pool:
      vmImage: ubuntu-latest
    variables:
      - group: TerraformServicePrincipal
    steps:
    - task: TerraformInstaller@0
      inputs:
        terraformVersion: 'latest'
    - task: TerraformCLI@0
      inputs:
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/DevOps/Infrastructure/Terraform'
        allowTelemetryCollection: true
    - task: TerraformCLI@0
      inputs:
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/DevOps/Infrastructure/Terraform'
        commandOptions: '-auto-approve'
        allowTelemetryCollection: true
      env:
        ARM_CLIENT_ID: $(ARM-CLIENT-ID)
        ARM_TENANT_ID: $(ARM-TENANT-ID)
        ARM_CLIENT_SECRET: $(ARM-CLIENT-SECRET)
        ARM_SUBSCRIPTION_ID: $(ARM-SUBSCRIPTION-ID)