trigger:
- main

resources:
- repo: self

# you have to setup a step to use powershell to get the storage key once you've setup the backend storage account
# key for the terraform state file

stages:
- stage: Provision
  displayName: 'Terraform Azure Environment'
  jobs: 
  - job: Provision
    displayName: 'Provisioning Container Instance'
    pool:
      vmImage: ubuntu-latest
    variables:
      - group: TerraformServicePrincipal
    steps:
