services:
  recipe-database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: SuperSecretPassw0rd
      MSSQL_PID: Developer
      MSSQL_AGENT_ENABLED: True
      MSSQL_TCP_PORT: 1433
  recipe-data:
    image: alfredoball/recipe.data:latest
    environment:
      DATASOURCE: recipe-database
      DATABASE: Recipe
      USERID: sa
      PASSWORD: SuperSecretPassw0rd
    depends_on:
      - recipe-database
    build:
      context: ${CONTEXT}
      dockerfile: "${DOCKER}/Recipe.Data.dockerfile"
  recipe-api:
    image: recipe.api:latest
    environment:
      DATASOURCE: recipe-database
      DATABASE: Recipe
      USERID: sa
      PASSWORD:
    depends_on:
      - recipe-data
    expose:
      - "5000"
    build:
      context: ${CONTEXT}
      dockerfile: "${DOCKER}/Recipe.API.dockerfile"
  recipe-web:
    profiles:
      - donotstart
    image: alfredoball/recipe.web:latest
    environment:
      BASE_URL:
    expose:
      - "8080"
    ports:
      - 8080:80
    build:
      context: ${CONTEXT}
      dockerfile: "${DOCKER}/Recipe.Web.dockerfile"
    volumes:
      - ${CONTEXT}/Services/Web/React:usr/src/app
  recipe-api-proxy:
    image: nginx:alpine
    volumes:
      - ./Recipe.API.nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - recipe-api
    ports:
      - "4000:4000"