# build the API - Run Tests - Produce Artifacts for the Deploy workflow

name: Build API
on:
  workflow_dispatch:
env:
  API_PROJECT_PATH: ./Services/API/Recipe.API.Entity
  API_PROJECT_FILE: Recipe.API.csproj
jobs:
  Build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.API_PROJECT_PATH }}
    steps:
      - uses: actions/checkout@v4
      - name: Build Project
        run: dotnet build ${{ env.API_PROJECT_FILE }}
      - uses: actions/upload-artifact@v4
      - name: Publish Artifact
        run: dotnet publish ${{ env.API_PROJECT_FILE }} -c Release -o release — nologo
        