name: Create and Publish Packages
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"
          source-url: https://nuget.pkg.github.com/alfredoball/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          PROJECT_PATH: ./Services/Data/Recipe.Data.Entity
          PROJECT_FILE: Recipe.Data.Entity.csproj
      - name: Build Project
        run: dotnet build format('{0}/{1}', $PROJECT_PATH, $PROJECT_FILE)
      - name: Create the Package
        run: dotnet pack --configuration Release format('{0}/{1}/bin/Release/*nupkg', $PROJECT_PATH, $PROJECT_FILE)
      # - name: Publish the Package to GPR
      #   run: dotnet nuget push {{ $PROJECT_PATH }}/bin/Release/*.nupkg