name: Create and Publish Packages
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PROJECT_PATH: ./Services/Data/Recipe.Data.Entity
      PROJECT_FILE: Recipe.Data.Entity.csproj
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"
          source-url: https://nuget.pkg.github.com/alfredoball/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Project
        working-directory: ${{ env.PROJECT_PATH }}
        run: dotnet build ${{ env.PROJECT_FILE }}
      - name: Create Package
        working-directory: ${{ env.PROJECT_PATH }}
        run: dotnet pack ${{ env.PROJECT_FILE }} --output nupkgs --configuration Release
        #  {{ format('{0}/{1}/bin/Release/*nupkg', env.PROJECT_PATH, env.PROJECT_FILE) }}
      # - name: Publish the Package to GPR
      #   run: dotnet nuget push {{ $PROJECT_PATH }}/bin/Release/*.nupkg